"""v2_evidence_driven

Revision ID: 68f39970ec67
Revises: 
Create Date: 2026-07-06 19:48:41.696735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '68f39970ec67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_summary', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('number_of_mentions', sa.Float(), nullable=True),
    sa.Column('source_diversity', sa.Float(), nullable=True),
    sa.Column('author_diversity', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ingestion_time', sa.DateTime(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_document_id', sa.UUID(), nullable=False),
    sa.Column('problem_cluster_id', sa.UUID(), nullable=True),
    sa.Column('exact_quote', sa.Text(), nullable=False),
    sa.Column('char_offset_start', sa.Float(), nullable=True),
    sa.Column('char_offset_end', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_cluster_id'], ['problem_clusters.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_cluster_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('who_has_problem', sa.Text(), nullable=True),
    sa.Column('what_workflow', sa.Text(), nullable=True),
    sa.Column('current_solution', sa.Text(), nullable=True),
    sa.Column('why_it_fails', sa.Text(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('competing_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('potential_ai_advantage', sa.Text(), nullable=True),
    sa.Column('potential_saas_advantage', sa.Text(), nullable=True),
    sa.Column('score_pain_severity', sa.Float(), nullable=True),
    sa.Column('score_workflow_frequency', sa.Float(), nullable=True),
    sa.Column('score_evidence_count', sa.Float(), nullable=True),
    sa.Column('score_source_diversity', sa.Float(), nullable=True),
    sa.Column('score_authority_weight', sa.Float(), nullable=True),
    sa.Column('score_recency', sa.Float(), nullable=True),
    sa.Column('score_switching_intent', sa.Float(), nullable=True),
    sa.Column('score_money_lost', sa.Float(), nullable=True),
    sa.Column('score_time_lost', sa.Float(), nullable=True),
    sa.Column('score_competition_saturation', sa.Float(), nullable=True),
    sa.Column('score_automation_potential', sa.Float(), nullable=True),
    sa.Column('score_confidence', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_cluster_id'], ['problem_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('COMPANY', 'PRODUCT', 'TECHNOLOGY', 'WORKFLOW', 'ROLE', 'INDUSTRY', 'COUNTRY', 'TEAM_SIZE', 'MARKET', 'COMPETITOR', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pain_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('MANUAL_WORK', 'TIME_WASTE', 'MONEY_LOSS', 'WORKFLOW_BREAKDOWN', 'BUG', 'POOR_UX', 'PRICING_COMPLAINT', 'MISSING_FEATURE', 'RELIABILITY', 'INTEGRATION', 'COMPLIANCE', 'SWITCHING_INTENT', 'VENDOR_LOCK_IN', 'WORKAROUND', 'PRODUCT_ABANDONMENT', 'LEARNING_CURVE', 'FALSE_PROMISE', name='painsignaltype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pain_signals')
    op.drop_table('observations')
    op.drop_table('entities')
    op.drop_table('opportunity_candidates')
    op.drop_table('evidences')
    op.drop_table('raw_documents')
    op.drop_table('problem_clusters')
    # ### end Alembic commands ###
