"""
clustering.py — Evidence clustering for Awoken V2.

Each new evidence is assigned to the nearest existing ProblemCluster
via cosine distance on embeddings. If no cluster is close enough,
a new cluster is created. Cluster metrics are updated incrementally.

Key design decisions:
- SIMILARITY_THRESHOLD: cosine *distance* (not similarity). 0.0 = identical.
  We use 0.40 to allow semantically related but not identical complaints to cluster.
  At 0.15 (old value), only near-duplicate text clustered, defeating the purpose.
- Theme summary: initialized from first quote. Regenerated by LLM after cluster
  reaches THEME_REGEN_THRESHOLD mentions (called synchronously for simplicity).
"""

from datetime import datetime, timezone
from sqlalchemy.orm import Session
from models import Evidence, ProblemCluster
from llm import generate_embedding, extract_json
from pydantic import BaseModel, Field
import numpy as np

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SIMILARITY_THRESHOLD = 0.40   # cosine distance; lower = stricter clustering
THEME_REGEN_THRESHOLD = 3     # regen LLM theme summary after N mentions


class ThemeSummarySchema(BaseModel):
    theme_summary: str = Field(
        description=(
            "A concise 8-12 word description of the shared problem in these quotes. "
            "E.g. 'Small businesses struggling with Salesforce pricing and complexity'. "
            "Do NOT invent details not present in the quotes."
        )
    )


def _regenerate_theme_summary(db: Session, cluster: ProblemCluster) -> None:
    """
    Uses LLM to synthesize a clean theme label from all quotes in the cluster.
    Called only when cluster crosses THEME_REGEN_THRESHOLD.
    """
    evidences = db.query(Evidence).filter(Evidence.problem_cluster_id == cluster.id).all()
    quotes = "\n".join(f"- {e.exact_quote}" for e in evidences)

    prompt = (
        "The following quotes all describe a related customer problem. "
        "Write a single concise theme label (8-12 words) that captures the shared pain.\n\n"
        f"Quotes:\n{quotes}"
    )

    try:
        result = extract_json(prompt, ThemeSummarySchema)
        if result and result.get("theme_summary"):
            cluster.theme_summary = result["theme_summary"]
    except Exception as e:
        print(f"[clustering] Theme regen failed for cluster {cluster.id}: {e}")
        # Non-fatal: keep the existing theme summary


def process_evidence_clustering(db: Session, evidence: Evidence) -> None:
    """
    Assigns evidence to the nearest ProblemCluster or creates a new one.

    Guarantees:
    - evidence.problem_cluster_id is set before returning
    - all cluster metrics (mentions, first/last seen, embedding) are updated
    - theme_summary is regenerated when cluster crosses THEME_REGEN_THRESHOLD
    """
    if not evidence.embedding:
        return

    # Normalize embedding to plain Python list (pgvector expects list[float])
    emb = evidence.embedding
    if hasattr(emb, "tolist"):
        emb = emb.tolist()
    else:
        emb = list(emb)
    evidence.embedding = emb

    # ── Find the closest existing cluster ──────────────────────────────────
    # We use raw SQL for the distance scalar to avoid calling .cosine_distance()
    # on a Python-side numpy array (which happens when SQLAlchemy returns a cached
    # ORM object with an already-loaded embedding attribute).

    evidence_emb_list = evidence.embedding  # already normalized to list above

    closest_cluster = (
        db.query(ProblemCluster)
        .filter(ProblemCluster.embedding.isnot(None))
        .order_by(ProblemCluster.embedding.cosine_distance(evidence_emb_list))
        .first()
    )

    now = datetime.now(timezone.utc)

    if closest_cluster is not None:
        # Compute distance via SQL scalar (avoids ORM object attribute)
        from sqlalchemy import text
        distance_row = db.execute(
            text(
                "SELECT embedding <=> CAST(:emb AS vector) AS dist "
                "FROM problem_clusters WHERE id = :cid"
            ),
            {"emb": str(evidence_emb_list), "cid": str(closest_cluster.id)},
        ).fetchone()
        distance = distance_row.dist if distance_row else None

        if distance is not None and distance < SIMILARITY_THRESHOLD:
            # ── Join existing cluster ────────────────────────────────────
            evidence.problem_cluster_id = closest_cluster.id

            # Update cluster embedding: weighted moving average
            n = closest_cluster.number_of_mentions
            current_emb = np.array(closest_cluster.embedding, dtype=np.float32)
            new_emb = np.array(evidence.embedding, dtype=np.float32)
            updated_emb = (current_emb * n + new_emb) / (n + 1)
            closest_cluster.embedding = updated_emb.tolist()

            # Update metrics
            closest_cluster.number_of_mentions = n + 1
            closest_cluster.last_seen = now
            if closest_cluster.first_seen is None:
                closest_cluster.first_seen = now

            # Update source diversity (distinct source count approximation)
            all_sources = set(
                e.raw_document.source
                for e in closest_cluster.evidences
                if e.raw_document
            )
            closest_cluster.source_diversity = float(len(all_sources))

            db.add(evidence)
            db.add(closest_cluster)
            db.flush()  # flush *after* setting cluster_id so it's visible

            # Regenerate theme summary at threshold
            if int(closest_cluster.number_of_mentions) == THEME_REGEN_THRESHOLD:
                _regenerate_theme_summary(db, closest_cluster)
                db.add(closest_cluster)

            db.commit()
            return

    # ── No close cluster found: create new ─────────────────────────────────
    new_cluster = ProblemCluster(
        theme_summary=evidence.exact_quote[:120] + ("..." if len(evidence.exact_quote) > 120 else ""),
        embedding=emb,  # use the normalized list
        number_of_mentions=1,
        source_diversity=1.0,
        first_seen=now,
        last_seen=now,
    )
    db.add(new_cluster)
    db.flush()  # get new_cluster.id

    evidence.problem_cluster_id = new_cluster.id
    db.add(evidence)
    db.commit()
