"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import Link from "next/link"
import { cn } from "@/lib/utils"
import {
  Lock, CalendarCheck, AlertTriangle, Clock, Workflow,
  Eye, Bot, ChartBar, Target, ArrowRight, CheckCircle2, Mail, Sparkles, Loader2,
} from "lucide-react"
import { BOOKING_URL } from "@/lib/constants"
import type { ReportResult, AssessmentAnswers } from "@/data/assessment"
import { PRIMARY, SECONDARY } from "./ui"

const findingIcons: Record<string, React.ElementType> = {
  clock: Clock, flow: Workflow, eye: Eye, bot: Bot, chart: ChartBar, target: Target,
}

const lockedItems = [
  "Revenue Leakage Analysis",
  "Root Cause Analysis",
  "AI Opportunity Map",
  "Automation Blueprint",
  "90-Day Implementation Plan",
  "Operational Maturity Report",
  "Department Analysis",
  "Employee Productivity Review",
  "Management Dashboard Recommendations",
  "Technology Recommendations",
  "Executive Summary PDF",
  "Business Intelligence Report",
  "ROI Forecast",
  "Implementation Timeline",
]

interface ReportProps {
  report: ReportResult
  answers: AssessmentAnswers
  permalink?: string
  onEmailMe?: () => Promise<void>
  emailSent?: boolean
}

export function ReportStep({ report, answers, permalink, onEmailMe, emailSent }: ReportProps) {
  const [sending, setSending] = useState(false)
  const healthColor = report.healthScore >= 75 ? "text-green" : report.healthScore >= 55 ? "text-amber-400" : "text-red-400"

  const handleEmail = async () => {
    if (!onEmailMe || sending) return
    setSending(true)
    try {
      await onEmailMe()
    } finally {
      setSending(false)
    }
  }

  return (
    <div className="w-full max-w-3xl mx-auto">
      <div className="mb-8 text-center">
        <h2 className="text-3xl sm:text-4xl md:text-5xl tracking-tight leading-[1.05] text-accent underline decoration-accent/40 underline-offset-8">
          Business Intelligence Report
        </h2>
        <p className="mt-3 text-sm text-muted-foreground">
          Prepared for <span className="font-semibold text-muted-foreground">{answers.businessName || "your business"}</span>
          {permalink && <span className="mx-1.5">·</span>}
          {permalink && (
            <a
              href={permalink}
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent underline underline-offset-4 transition-colors duration-200 hover:text-accent/80"
            >
              {permalink.replace("https://www.awoken.in/", "")}
            </a>
          )}
        </p>
        {permalink && (
          <p className="mt-1 text-xs text-muted-foreground">
            Generated by the Awoken Intelligence Engine
          </p>
        )}
      </div>

      <section className="rounded-2xl border border-border bg-card p-6 sm:p-8">
        <div className="flex flex-col sm:flex-row items-center gap-8">
          <ScoreRing score={report.healthScore} />
          <div className="flex-1 w-full">
            <p className={cn("text-xl font-bold", healthColor)}>
              {report.healthScore >= 75 ? "Healthy — but leaking quietly" : report.healthScore >= 55 ? "Operational — significant upside available" : "Fragile — major opportunities identified"}
            </p>
            <div className="mt-5 grid grid-cols-2 gap-3">
              <Metric label="Operational Maturity" value={`${report.maturityScore} · ${report.maturityTier} Tier`} />
              <Metric label="AI Readiness" value={`${report.aiReadiness}%`} />
              <Metric label="Management Visibility" value={`${catScore(report, "visibility")}%`} />
              <Metric label="Lead Management" value={`${catScore(report, "leadManagement")}%`} />
            </div>
          </div>
        </div>

        <div className="mt-7 grid grid-cols-3 gap-3 border-t border-border pt-6">
          <EstimatePill label="Risk Level" value={report.riskLevel} tone={report.riskLevel === "Low" ? "good" : report.riskLevel === "Moderate" ? "mid" : "bad"} />
          <EstimatePill label="Opportunity" value={report.opportunityLevel} tone={report.opportunityLevel === "High" ? "good" : "mid"} />
          <EstimatePill label="Operational Impact" value={report.impactLevel} tone="mid" />
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
        <SectionTitle>Executive Summary</SectionTitle>
        <p className="text-[15px] sm:text-base leading-relaxed text-muted-foreground">{report.executiveSummary}</p>
      </section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
        <SectionTitle>Business Health Matrix</SectionTitle>
        <div className="flex flex-col sm:flex-row items-center gap-8">
          <RadarChart categories={report.categories} />
          <div className="w-full flex-1 space-y-3">
            {report.categories.map((c) => (
              <div key={c.key}>
                <div className="mb-1.5 flex items-center justify-between">
                  <span className="text-sm font-medium text-muted-foreground">{c.label}</span>
                  <span className="text-sm font-bold tabular-nums text-foreground">{c.score}</span>
                </div>
                <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                  <motion.div
                    className="h-full rounded-full bg-gradient-to-r from-[#F97316] to-[#fb923c]"
                    initial={{ width: 0 }}
                    animate={{ width: `${c.score}%` }}
                    transition={{ duration: 1, ease: [0.25, 0.1, 0.25, 1], delay: 0.2 }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
        <SectionTitle>Top Three Bottlenecks</SectionTitle>
        <div className="space-y-4">
          {report.bottlenecks.map((b, i) => {
            const Icon = findingIcons[["clock", "flow", "eye"][i]] ?? Target
            return (
              <div key={b.title} className="rounded-xl border border-border bg-background p-5">
                <div className="flex flex-wrap items-start gap-3">
                  <div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-accent/15">
                    <Icon className="size-4.5 text-accent" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-[15px] font-bold text-foreground">Finding #{i + 1} — {b.title}</p>
                    <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{b.detail}</p>
                  </div>
                </div>
                <div className="mt-4 flex flex-wrap gap-2">
                  <Chip label="Impact" value={b.impact} tone={b.impact === "High" ? "bad" : "mid"} />
                  <Chip label="Confidence" value={`${b.confidence}%`} tone="neutral" />
                  <Chip label="Est. Business Impact" value={b.estimatedImpact} tone={b.estimatedImpact === "Significant" ? "bad" : "mid"} />
                </div>
              </div>
            )
          })}
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
        <SectionTitle>Benchmark Comparison</SectionTitle>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[480px] text-sm">
            <thead>
              <tr className="border-b border-border text-left">
                <th className="pb-3 pr-4 font-semibold text-muted-foreground">Metric</th>
                <th className="pb-3 pr-4 font-semibold text-foreground">Your Business</th>
                <th className="pb-3 pr-4 font-semibold text-muted-foreground">Industry Median</th>
                <th className="pb-3 font-semibold text-muted-foreground">Top Performers</th>
              </tr>
            </thead>
            <tbody>
              {report.benchmarks.map((b) => (
                <tr key={b.label} className="border-b border-border/60 last:border-0">
                  <td className="py-3.5 pr-4 font-medium text-muted-foreground">{b.label}</td>
                  <td className="py-3.5 pr-4">
                    <span className="font-bold text-accent">{b.yours}</span>
                  </td>
                  <td className="py-3.5 pr-4 text-muted-foreground">{b.industryMedian}</td>
                  <td className="py-3.5 text-muted-foreground">{b.topPerformers}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-4 space-y-2.5">
          {report.benchmarks.map((b) => (
            <div key={b.label} className="flex items-center gap-3">
              <span className="w-36 shrink-0 text-xs font-medium text-muted-foreground">{b.label}</span>
              <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted">
                <motion.div
                  className="h-full rounded-full bg-accent/70"
                  initial={{ width: 0 }}
                  animate={{ width: `${b.progress}%` }}
                  transition={{ duration: 1, delay: 0.3 }}
                />
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
        <SectionTitle>Revenue Opportunity Heatmap</SectionTitle>
        <p className="mb-5 text-xs text-muted-foreground">Higher bar = bigger untapped opportunity</p>
        <div className="space-y-4">
          <HeatRow label="Lead Response" level={10 - catScore(report, "leadManagement") / 10} />
          <HeatRow label="Follow-up" level={10 - catScore(report, "customerJourney") / 10} />
          <HeatRow label="Reporting" level={10 - catScore(report, "reporting") / 10} />
          <HeatRow label="Automation" level={10 - catScore(report, "automation") / 10} />
          <HeatRow label="CRM" level={10 - catScore(report, "salesOperations") / 10} />
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-8">
        <SectionTitle>Quick Wins</SectionTitle>
        <div className="grid gap-4 sm:grid-cols-3">
          {report.quickWins.map((win, i) => (
            <motion.div
              key={win.title}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + i * 0.1 }}
              className="rounded-xl border border-border bg-background p-5"
            >
              <div className="mb-3 flex size-8 items-center justify-center rounded-lg bg-emerald-500/15">
                <ZapIcon />
              </div>
              <p className="text-sm font-bold leading-snug text-foreground">{win.title}</p>
              <div className="mt-3 flex flex-wrap gap-1.5">
                <MiniChip tone="good">{win.difficulty}</MiniChip>
                <MiniChip tone="bad">{win.impact}</MiniChip>
                <MiniChip tone="neutral">{win.timeline}</MiniChip>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      <section className="mt-8">
        <div className="mb-5 flex items-center gap-2.5">
          <Lock className="size-4 text-muted-foreground" />
          <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
            Unlocked during your strategy session
          </p>
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          {lockedItems.map((item) => (
            <div key={item} className="relative select-none overflow-hidden rounded-xl border border-border bg-card p-4">
              <div className="absolute inset-0 opacity-50 blur-[6px]">
                <div className="h-full w-full bg-gradient-to-r from-black/[0.06] via-black/[0.03] to-black/[0.06]" />
                <div className="absolute inset-x-0 top-1/2 h-px bg-black/10" />
                <div className="absolute inset-y-0 left-1/3 w-px bg-muted" />
              </div>
              <div className="relative flex items-center justify-between">
                <span className="text-sm font-semibold text-muted-foreground">{item}</span>
                <Lock className="size-4 text-muted-foreground" />
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-10 rounded-2xl border border-accent/20 bg-gradient-to-b from-[#F97316]/[0.08] to-transparent p-8 sm:p-12 text-center">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="mx-auto max-w-xl"
        >
          <Sparkles className="mx-auto mb-5 size-8 text-accent" />
          <h3 className="text-2xl sm:text-3xl font-bold tracking-tight text-foreground leading-tight">
            Your business has significant untapped operational potential
          </h3>
          <p className="mt-4 text-[15px] leading-relaxed text-muted-foreground">
            We identified <span className="font-bold text-foreground">17 improvement opportunities</span>. Only{" "}
            <span className="font-bold text-accent">3 need immediate attention</span>. During your complimentary
            strategy session we&apos;ll review every finding, explain the reasoning behind each recommendation,
            estimate the business impact, and show exactly how we&apos;d implement the improvements.
          </p>
          <div className="mt-6 grid gap-2.5 text-left sm:grid-cols-2">
            {[
              "Walk through every finding",
              "Explain root causes",
              "Estimate financial impact",
              "Design your implementation roadmap",
            ].map((t) => (
              <p key={t} className="flex items-center gap-2.5 text-sm text-muted-foreground">
                <CheckCircle2 className="size-4 shrink-0 text-accent" /> {t}
              </p>
            ))}
          </div>
          <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Link href={BOOKING_URL} className={cn(PRIMARY, "w-full sm:w-auto px-8")}>
              <CalendarCheck className="size-4" />
              Book Free Strategy Session
            </Link>
            <button
              type="button"
              onClick={handleEmail}
              disabled={sending || emailSent}
              className={cn(SECONDARY, "w-full sm:w-auto")}
            >
              {sending ? <Loader2 className="size-4 animate-spin" /> : <Mail className="size-4" />}
              {emailSent ? "Preview Sent ✓" : "Email Me My Preview Report"}
            </button>
          </div>
          {permalink && (
            <p className="mt-5 text-xs text-muted-foreground">
              Report link: <span className="text-muted-foreground">{permalink}</span>
            </p>
          )}
          <p className="mt-3 flex items-center justify-center gap-1.5 text-xs text-muted-foreground">
            <AlertTriangle className="size-3.5" /> Free · No obligation · 30–45 minutes
          </p>
        </motion.div>
      </section>
    </div>
  )
}

function catScore(report: ReportResult, key: string) {
  return report.categories.find((c) => c.key === key)?.score ?? 0
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return <h3 className="mb-5 text-sm font-semibold uppercase tracking-widest text-muted-foreground">{children}</h3>
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-background p-3.5">
      <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p>
      <p className="mt-1 text-base font-bold tabular-nums text-foreground">{value}</p>
    </div>
  )
}

function EstimatePill({ label, value, tone }: { label: string; value: string; tone: "good" | "mid" | "bad" }) {
  return (
    <div className="text-center">
      <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p>
      <p className={cn(
        "mt-1 text-base font-bold",
        tone === "good" ? "text-green" : tone === "bad" ? "text-red-400" : "text-amber-400"
      )}>
        {value}
      </p>
    </div>
  )
}

function Chip({ label, value, tone }: { label: string; value: string; tone: "good" | "mid" | "bad" | "neutral" }) {
  return (
    <span className={cn(
      "flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-semibold",
      tone === "good" && "border-emerald-500/20 bg-emerald-500/10 text-green",
      tone === "bad" && "border-red-500/20 bg-red-500/10 text-red-400",
      tone === "mid" && "border-amber-500/20 bg-amber-500/10 text-amber-400",
      tone === "neutral" && "border-border bg-black/[0.05] text-muted-foreground",
    )}>
      <span className="font-normal text-muted-foreground">{label}:</span> {value}
    </span>
  )
}

function MiniChip({ children, tone }: { children: React.ReactNode; tone: "good" | "bad" | "neutral" }) {
  return (
    <span className={cn(
      "rounded-full border px-2.5 py-0.5 text-[11px] font-semibold",
      tone === "good" && "border-emerald-500/20 bg-emerald-500/10 text-green",
      tone === "bad" && "border-accent/20 bg-accent/10 text-accent",
      tone === "neutral" && "border-border bg-black/[0.05] text-muted-foreground",
    )}>
      {children}
    </span>
  )
}

function ZapIcon() {
  return <ArrowRight className="size-4 text-green" />
}

function ScoreRing({ score }: { score: number }) {
  const radius = 70
  const circumference = 2 * Math.PI * radius
  const offset = circumference * (1 - score / 100)
  return (
    <div className="relative size-44 shrink-0 sm:size-48">
      <svg viewBox="0 0 164 164" className="size-full -rotate-90">
        <circle cx="82" cy="82" r={radius} fill="none" strokeWidth="10" className="stroke-muted" />
        <motion.circle
          cx="82" cy="82" r={radius} fill="none" strokeWidth="10" strokeLinecap="round"
          className="stroke-[#F97316]"
          strokeDasharray={circumference}
          initial={{ strokeDashoffset: circumference }}
          animate={{ strokeDashoffset: offset }}
          transition={{ duration: 1.6, ease: [0.25, 0.1, 0.25, 1], delay: 0.3 }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <motion.span
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 1.2 }}
          className="text-5xl font-black tabular-nums tracking-tight text-foreground"
        >
          {score}
        </motion.span>
        <span className="mt-1 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">Health Score</span>
      </div>
    </div>
  )
}

function RadarChart({ categories }: { categories: ReportResult["categories"] }) {
  const size = 240
  const center = size / 2
  const radius = 92
  const labels = categories
  const n = labels.length

  const point = (i: number, r: number) => {
    const angle = (Math.PI * 2 * i) / n - Math.PI / 2
    return [center + r * Math.cos(angle), center + r * Math.sin(angle)] as const
  }

  const polygon = (r: number) => labels.map((_, i) => point(i, r).join(",")).join(" ")

  const dataPolygon = labels
    .map((c, i) => point(i, (c.score / 100) * radius).join(","))
    .join(" ")

  return (
    <div className="relative shrink-0">
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
        {[0.25, 0.5, 0.75, 1].map((p) => (
          <polygon key={p} points={polygon(radius * p)} fill="none" stroke="rgba(255,255,255,0.08)" />
        ))}
        {labels.map((_, i) => {
          const [x, y] = point(i, radius + 14)
          return <line key={i} x1={center} y1={center} x2={x} y2={y} stroke="rgba(255,255,255,0.06)" />
        })}
        <polygon points={dataPolygon} fill="rgba(249,115,22,0.15)" stroke="#F97316" strokeWidth="2" strokeLinejoin="round" />
        {labels.map((c, i) => {
          const [x, y] = point(i, (c.score / 100) * radius)
          return <circle key={c.key} cx={x} cy={y} r="3" fill="#F97316" />
        })}
      </svg>
      <div className="absolute inset-0 flex flex-wrap items-end justify-center gap-x-3 gap-y-1 pb-2">
        {labels.map((c) => (
          <span key={c.key} className="text-[10px] font-semibold text-muted-foreground">{c.label}</span>
        ))}
      </div>
    </div>
  )
}

function HeatRow({ label, level }: { label: string; level: number }) {
  const clamped = Math.max(0, Math.min(10, level))
  const pct = clamped * 10
  return (
    <div className="flex items-center gap-3">
      <span className="w-24 shrink-0 text-xs font-semibold text-muted-foreground">{label}</span>
      <div className="h-4 flex-1 overflow-hidden rounded-md bg-black/[0.06]">
        <motion.div
          className={cn("h-full rounded-md", pct >= 70 ? "bg-red-500/80" : pct >= 45 ? "bg-amber-500/80" : "bg-emerald-500/70")}
          initial={{ width: 0 }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.9, ease: [0.25, 0.1, 0.25, 1] }}
        />
      </div>
      <span className="w-8 shrink-0 text-right text-xs font-bold tabular-nums text-muted-foreground">{Math.round(clamped)}</span>
    </div>
  )
}
